name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "pypy-3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipfile-requirements flake8 lintly mypy lxml pytest pytest-cov pipx
          pipx install poetry
          poetry export -f requirements.txt --output requirements.txt
          pip install -r requirements.txt
      - if: ${{ github.event_name == 'push'}}
        name: Lint with flake8
        run: flake8 ./bite_di
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.python-version == '3.7' && github.event_name != 'push' }}
        name: Lint with flake8
        run: flake8 ./bite_di | lintly
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.python-version != '3.7' && github.event_name != 'push' }}
        name: Lint with flake8
        run: flake8 ./bite_di
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.python-version == '3.10' && github.event_name == 'push' }}
        name: Lint with flake8
        run: flake8 ./tests
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.python-version == '3.10'  && github.event_name != 'push'}}
        name: Lint with flake8
        run: flake8 ./tests | lintly
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.python-version != 'pypy-3.8' }}
        name: Check types with mypy
        run: mypy -p bite_di --cobertura-xml-report .
        #https://img.shields.io/static/v1?label=mypy&message=checked&color=blue&logo=data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTQiIGhlaWdodD0iMTQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIj4KIDxtZXRhZGF0YSBpZD0ibWV0YWRhdGE3Ij5pbWFnZS9zdmcreG1sPC9tZXRhZGF0YT4KCiA8Zz4KICA8dGl0bGU+TGF5ZXIgMTwvdGl0bGU+CiAgPHBhdGggc3Ryb2tlPSJudWxsIiBmaWxsLXJ1bGU9Im5vbnplcm8iIGZpbGw9IiMyYTZkYjIiIGQ9Im03LjAwOTU4LDBjLTMuNTIwODUsMCAtMy4zMDA5OSwxLjUzNjY3IC0zLjMwMDk5LDEuNTM2NjdsMC4wMDM5MiwxLjU5MTk4bDMuMzU5ODYsMGwwLDAuNDc3OTlsLTQuNjk0MzksMGMwLDAgLTIuMjUyOTksLTAuMjU3MTUgLTIuMjUyOTksMy4zMTgyN2MwLDMuNTc1NDIgMS45NjY0NiwzLjQ0ODYzIDEuOTY2NDYsMy40NDg2M2wxLjE3MzYsMGwwLC0xLjY1OTEzYzAsMCAtMC4wNjMyNiwtMS45NzkxMSAxLjkzNTA2LC0xLjk3OTExYzEuOTk4MzIsMCAzLjMzMjM5LDAgMy4zMzIzOSwwYzAsMCAxLjg3MjI2LDAuMDMwNDYgMS44NzIyNiwtMS44MjExYzAsLTEuODUxNTYgMCwtMy4wNjE1IDAsLTMuMDYxNWMwLDAgMC4yODQyNiwtMS44NTI3IC0zLjM5NTE5LC0xLjg1MjdsMCwwbDAuMDAwMDEsMHptLTEuODUyNjMsMS4wNzA1NGMwLjMzNDI4LDAgMC42MDQ0NiwwLjI3MTkyIDAuNjA0NDYsMC42MDgzNWMwLDAuMzM2NDMgLTAuMjcwMTgsMC42MDgzNSAtMC42MDQ0NiwwLjYwODM1Yy0wLjMzNDI4LDAgLTAuNjA0NDYsLTAuMjcxOTIgLTAuNjA0NDYsLTAuNjA4MzVjMCwtMC4zMzY0MyAwLjI3MDE4LC0wLjYwODM1IDAuNjA0NDYsLTAuNjA4MzV6IiBpZD0icGF0aDg2MTUiLz4KICA8cGF0aCBzdHJva2U9Im51bGwiIGZpbGwtcnVsZT0ibm9uemVybyIgZmlsbD0iI2RmZGZkZiIgaWQ9InBhdGg4NjIwIiBkPSJtNy4xMDk1NywxMy44ODU2NmMzLjUyMDg1LDAgMy4zMDA5OSwtMS41MzY2NyAzLjMwMDk5LC0xLjUzNjY3bC0wLjAwMzkyLC0xLjU5MTk4bC0zLjM1OTg2LDBsMCwtMC40Nzc5OWw0LjY5NDM5LDBjMCwwIDIuMjUyOTksMC4yNTcxNSAyLjI1Mjk5LC0zLjMxODI3YzAsLTMuNTc1NDIgLTEuOTY2NDYsLTMuNDQ4NjMgLTEuOTY2NDYsLTMuNDQ4NjNsLTEuMTczNiwwbDAsMS42NTkxM2MwLDAgMC4wNjMyNiwxLjk3OTExIC0xLjkzNTA2LDEuOTc5MTFjLTEuOTk4MzIsMCAtMy4zMzIzOSwwIC0zLjMzMjM5LDBjMCwwIC0xLjg3MjI2LC0wLjAzMDQ2IC0xLjg3MjI2LDEuODIxMWMwLDEuODUxNTUgMCwzLjA2MTQ5IDAsMy4wNjE0OWMwLDAgLTAuMjg0MjYsMS44NTI3IDMuMzk1MTksMS44NTI3bDAsMGwtMC4wMDAwMSwwLjAwMDAxem0xLjg1MjYzLC0xLjA3MDU0Yy0wLjMzNDI4LDAgLTAuNjA0NDYsLTAuMjcxOTIgLTAuNjA0NDYsLTAuNjA4MzVjMCwtMC4zMzY0MyAwLjI3MDE4LC0wLjYwODM1IDAuNjA0NDYsLTAuNjA4MzVjMC4zMzQyOCwwIDAuNjA0NDYsMC4yNzE5MiAwLjYwNDQ2LDAuNjA4MzVjMCwwLjMzNjQzIC0wLjI3MDE4LDAuNjA4MzUgLTAuNjA0NDYsMC42MDgzNXoiLz4KIDwvZz4KPC9zdmc+
        #https://codecov.io/api/gh/opengeekv2/bite_di
      - uses: codecov/codecov-action@v2
        with:
          files: cobertura.xml
          flags: type-coverage
      - name: Test with pytest
        run: python -m pytest --cov=bite_di --cov-report=xml
      - uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          flags: test-coverage